### PR TITLE
Added the OS Protocol

### PR DESCRIPTION
**Pull request by RichardLitt**
From [osprotocol.com](http://osprotocol.com).

Disclaimer: I technically made the protocol, but it's had feedback and adoption elsewhere.

### CODE REVIEW

**Comment by nocarryr** [comment]
@RichardLitt the URL in your description uses HTTPS, but fails to load with that scheme, only HTTP. Just thought you may want to know.

**Comment by RichardLitt** [comment]
@nocarryr Huh! I used the `(//osprotocol.com)` notation, didn't realize that that defaults to HTTPS. Thanks!

**Comment by joshbuchea** [comment]
@RichardLitt I really like the idea of the OS Protocol. I really want to accept this pull request, but because of the low level of adoption I don't think I can accept this right now. I wish you the best with the OS Protocol. I ⭐'d your repo and tweeted a link. Thanks @RichardLitt!

**Comment by RichardLitt** [comment]
Thanks anyway. I figured it wouldn't hurt to try. :)

**Comment by RichardLitt** [comment]
@joshbuchea Given the much more extensive length of this repo now, maybe this might be something worth considering again? Totally understand if not.

**Comment by dodekeract** [comment]
@RichardLitt `//` doesn't default to HTTPS. It uses the same as the website you're using it on. Since GitHub uses HTTPS, `//` will use HTTPS.

**Comment by RichardLitt** [comment]
@dodekeract Good to know! Thanks.

**Pull request closed without merging**
