### PR TITLE
Ontologies

### PR DESCRIPTION
**Pull request by dcondrey**
Extensive additions including ontologies such as Dublin Core, OWL, FOAF; further Open Graph tags; deprecated Netscape tags; CSRF token tags; etc..

### CODE REVIEW

**Comment by dcondrey** [comment]
Satisfies issue #15

**Comment by dcondrey** [comment]
Adding more ontologies and deprecated tags and descriptions.

**Comment by dcondrey** [comment]
Resolved merge conflicts.  Confirmed to contribution guidelines.  Added more content.  There are many more tags available here https://wiki.whatwg.org/wiki/MetaExtensions which I have not added yet.

**Comment by dcondrey** [comment]
Additionally, pragma-directions are listed here:  https://html.spec.whatwg.org/multipage/semantics.html#other-metadata-names

**Comment by dcondrey** [comment]
Example of rdf content in head https://html.spec.whatwg.org/multipage/dom.html#metadata-content-2

``` html
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:r="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xml:lang="en">
 <head>
  <title>Hedral's Home Page</title>
  <r:RDF>
   <Person xmlns="http://www.w3.org/2000/10/swap/pim/contact#"
           r:about="http://hedral.example.com/#">
    <fullName>Cat Hedral</fullName>
    <mailbox r:resource="mailto:hedral@damowmow.com"/>
    <personalTitle>Sir</personalTitle>
   </Person>
  </r:RDF>
 </head>
 <body>
  <h1>My home page</h1>
  <p>I like playing with string, I guess. Sister says squirrels are fun
  too so sometimes I follow her to play with them.</p>
 </body>
</html>
```

**Comment by dcondrey** [comment]
?

**Comment by joshbuchea** [comment]
@dcondrey wow! There is a lot here. Unfortunately, I can't accept this because there are too many changes in this PR. And the code comments appear very high quality & helpful, but I think they're a bit too verbose.

I would love to get some of this (dublin core, csrf, micro id, etc.) in the project though and I encourage you to submit new individual pull requests for these changes.

I really appreciate the effort here. Don't blame you if you're like "screw that guy", but no offense intended and please don't be discouraged from contributing!

**Pull request closed without merging**
