### PR TITLE
add cache-control meta tags

### PR DESCRIPTION
**Pull request by skb1129**
I added Cache-Control, Pragma and Expires meta tags that are used to control the browser cache of the webpage.

### CODE REVIEW

**Comment by scottaohara** [comment]
From the quick research I've done on them, they appear to be primarily supported by Internet Explorer (no mention of Edge, as the published dates of the documentation I found predate Edge).  

Do you have any current resources that indicate that these meta tags are recognized beyond Internet Explorer?

Thanks!

**Comment by skb1129** [comment]
https://wp-mix.com/disable-caching-html/

This is the link to the latest post that I could find.
I added these tags because I used them myself very recently on Google Chrome v61.0 and Firefox Developer Edition v57.0 and they worked fine.

http://suryakantbansal.me/web-development/

This is the project in which I used these tags, you can test this yourself.
Here is the link to its source code => https://github.com/skb1129/web-development/tree/master/docs

**Comment by skb1129** [comment]
https://wp-mix.com/disable-caching-html/

This is the link to the latest post that I could find.I added these tags because I used them myself very recently on Google Chrome v61.0 and Firefox Developer Edition v57.0 and they worked fine.

ES6-Project

This is the project in which I used these tags, you can test this yourself.Here is the link to its source code => https://github.com/skb1129/web-development/tree/master/docs

    On Wednesday 1 November 2017, 12:54:48 AM IST, scottaohara <notifications@github.com> wrote:  
 
 
From the quick research I've done on them, they appear to be primarily supported by Internet Explorer (no mention of Edge, as the published dates of the documentation I found predate Edge).

Do you have any current resources that indicate that these meta tags are recognized beyond Internet Explorer?

Thanks!

**Comment by skb1129** [comment]
I dig some more information and found out that these doesn't work anymore. To control the cache, we must send the request in HTTP header.

**Pull request closed without merging**
