### PR TITLE
Feature: compress.html

### PR DESCRIPTION
**Pull request by marcobiedermann**
Add [compress.html](https://github.com/penibelst/jekyll-compress-html) layout.
You already added some configuration for this it.

### CODE REVIEW

**Comment by joshbuchea** [comment]
@marcobiedermann apologies for not getting back to you sooner man. I actually left out the compress html step intentionally. Good lookin' out though man 🙌

**Comment by marcobiedermann** [comment]
@joshbuchea That is absolutely fine. May I ask why? I am always interested in other people's opinion :)

**Comment by joshbuchea** [comment]
@marcobiedermann I like my markup thick n' chunky :) And I believe any gains beyond gzip are minimal.

**Comment by marcobiedermann** [comment]
@joshbuchea Alright, thank for your explanation.

**Pull request closed without merging**
