### PR TITLE
Add content of 360 browser

### PR DESCRIPTION
**Pull request by Dafrok**
360 browser can switch its render engine by this meta tag.

http://se.360.cn/
http://se.360.cn/v6/help/meta.html

### CODE REVIEW

**Comment by ylc395** [comment]
author said that he has no interested in 360Browser in #38 
if @joshbuchea is willing to add some content about some types of Chinese browers, I'd like to do some collection job about QQ browser/360 browser/UC browser, which are popular browsers in China.

**Comment by jamalabdillah** [comment]
On pull request

**Comment by joshbuchea** [comment]
@ylc395 it seems there is a fair amount of interest in adding content for Chinese browsers. If you can keep the html small and limit the scope to only the most popular Chinese browsers, I would like to take you up on your offer.

**Comment by joshbuchea** [comment]
I'll go ahead and accept this PR for now. Thanks for your contribution @Dafrok!

**Comment by Dafrok** [comment]
Thank you for your great work!

**Comment by jamalabdillah** [comment]
Helpful

**Pull request merged**
