### PR TITLE
Added verificatin codes for . 1.Yandex 2.Bing 3.Alexa 4.Pinterese 5.N…

### PR DESCRIPTION
**Pull request by bhaskarmelkani**
…orton Safe Web

### CODE REVIEW

**Comment by TraderStf** [comment]
All these verification codes are required only once, when they verify you are the owner.
After that single check, you can delete them.
To be more precise, you can add them to only one page, then delete them.

Most also propose the alternative to add a text file with the token, after the verification, this file can also be removed.

A lot of sites are keeping these useless items after the verification...

**Comment by sexyass** [comment]
Damn

**Comment by marcobiedermann** [comment]
@bhaskarmelkani Could you please merge `master` into your changes to keep it up to date?!

**Comment by StudioJunkyard** [comment]
@TraderStf have you got sources on this info, I'd like to learn more.

**Comment by TraderStf** [comment]
@StudioJunkyard each one is explained, sometimes not very clearly, on the corresponding sites.
But try, add a file or a tag, verify it by the search engine.
Remove it, the search engine mgt tools don't complain.

Some are even including that meta in each page, lot of waste of bytes and electricity to carry useless info 😜

**Comment by bhaskarmelkani** [comment]
Apologies for the delayed reply. I have updated the branch and merged with master.

**Comment by joshbuchea** [comment]
@bhaskarmelkani apologies for taking nearly a year to get this merged. Thanks for your contribution!

**Comment by bhaskarmelkani** [comment]
@joshbuchea no worries :)

**Pull request merged**
