### PR TITLE
X-UA-Compatible meta tag must be first in the <head> element

### PR DESCRIPTION
**Pull request by thisconnect**
http://stackoverflow.com/questions/6156639/x-ua-compatible-is-set-to-ie-edge-but-it-still-doesnt-stop-compatibility-mode#answer-9624500

### CODE REVIEW

**Comment by joshbuchea** [comment]
Do you have any other references to support your claim? I'm not convinced by that Stackoverflow thread.

**Comment by thisconnect** [comment]
I am not happy about it either. We had this issue only with intranet pages where the network team couldn't change the config due to other MS services. IIR old sharepoint was the reason they wouldn't change it.

Placing the X-UA-Compatible meta tag first fixed it. 
Maybe a comment instead of chainging the order is better?
```html
<meta http-equiv="x-ua-compatible" content="ie=edge"><!-- if intranet settings force Compatibility View place this first -->
```

**Comment by thisconnect** [comment]
Related: you can't have comments before the X-UA-Compatible meta tag https://github.com/h5bp/html5-boilerplate/issues/1187

Which at one point the HTML5 boilerplate had the conditional comment around the `<body>` before the completely remove it.

**Comment by thisconnect** [comment]
- https://www.drupal.org/node/1527990
- http://tesmond.blogspot.ch/2011/10/ie9-intranet-compatibility-mode-in.html#!/2011/10/ie9-intranet-compatibility-mode-in.html
(Sorry for spamming)

**Comment by ThaDafinser** [comment]
In general this is really helpful:
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/ieblog/2010/Mar/02_HowIE8DeterminesDocumentMode_3.png

I tried it now in IE11 and recogniced no difference?

**Comment by joshbuchea** [comment]
Thank you for the additional references. Although I'd prefer to see something from a respected source, preferably something more recent. Stackoverflow threads and older random blog posts are not the greatest sources.

I believe that html comments before the tag will cause issue, but I'm not convinced the current order of the tags is an issue.

**Pull request closed without merging**
