### PR TITLE
Add link tag for the W3C App Manifest specification

### PR DESCRIPTION
**Pull request by justmarkup**

### CODE REVIEW

**Comment by joshbuchea** [comment]
Looks good 👍

**Comment by joshbuchea** [comment]
Thanks @justmarkup!

**Comment by scshepard** [comment]
Hi, this is an interesting feature, for sure, but does someone have a w3c document that explains the purpose for a meta theme?thanks!steve

Date: Thu, 21 Apr 2016 00:00:39 -0700

**Comment by justmarkup** [comment]
@scshepard You can find the specification here: https://www.w3.org/TR/2016/WD-appmanifest-20160331/

This specification defines a JSON-based manifest file that provides developers with a centralized place to put metadata associated with a web application. This metadata includes, but is not limited to, the web application's name, links to icons, as well as the preferred URL to open when a user launches the web application.

**Comment by scshepard** [comment]
Thanks all! Never a dull moment in web dev's life...

Date: Thu, 21 Apr 2016 00:22:25 -0700

**Pull request merged**
