### PR TITLE
Recommended minimal tags

### PR DESCRIPTION
**Pull request by olscore**
I think you should add a section for the minimal websites to clarify which tags are essential. I would argue that these 5 tags are pretty much a necessity for most websites today. The first 3 especially, the last 2 being of lesser importance but still pretty critical and easy to implement. Just my recommendation.

### CODE REVIEW

**Comment by joshbuchea** [comment]
@olscore I think this is an excellent idea and I think others would definitely appreciate this. If you'd be willing to make a couple of small changes, I'd be happy to accept this PR. Could you:

- Move title tag below meta tags
- Remove the canonical link

I understand the importance of the canonical link element, but I would prefer to keep this as minimal as possible. If you're cool with my suggestions, just make the changes and I'll accept. Thanks for your contribution!

**Comment by olscore** [comment]
Cool thanks. Sorry about the extra commits, probably want consistent formatting. Feel free to close this PR if it's too cumbersome, don't really need credit. But feel free to merge if this looks good. Cheers.

**Comment by hypeJunction** [comment]
@olscore I have hijacked and squashed your PR here: #88

**Comment by hypeJunction** [comment]
To squash commits in the future:

```sh
# do this once in the repo
git remote add upstream https://github.com/joshbuche/HEAD.git
```

```sh
# do this for each PR your want to make
git fetch upstream
git checkout -b my-pull-request
git reset --hard upstream/master

# add your fixes

git commit -a -m 'My fixes'
```

```sh

# oops I did something wrong
git fetch upstream
git rebase -i upstrem/master

# do your vim magic using instructions (in this case change pick to squash

# force update your origin
git push --force origin my-pull-request
```

**Comment by olscore** [comment]
Haha I used the Github website instead of native git because I'm lazy. Thanks.

**Comment by joshbuchea** [comment]
Thanks @olscore & @hypeJunction! Appreciate the contribution.

**Pull request closed without merging**
