### PR TITLE
add "sublime-head-snippets" to related projects

### PR DESCRIPTION
**Pull request by marcobiedermann**
As mentioned in #115, I created a Sublime Text snippets package for this project.

### CODE REVIEW

**Comment by joshbuchea** [comment]
Awesome! Thanks for doing this @marcobiedermann!

**Comment by marcobiedermann** [comment]
@joshbuchea You are very welcome. Still have to wait for the approval on [package_control_channel](https://github.com/wbond/package_control_channel/pull/5576).

**Comment by joshbuchea** [comment]
👍 Ping me once it's approved and I'll tweet a link.

**Comment by marcobiedermann** [comment]
@joshbuchea Thanks man! Sure, I will hit you up

**Pull request merged**
