### PR TITLE
add contributing.md to allow solid contribution other developers.

### PR DESCRIPTION
**Pull request by Oluwasetemi**

### CODE REVIEW

**Comment by joshbuchea** [comment]
@Oluwasetemi GitHub tracks contributors automatically. Project contributors can viewed in the repo's [contributors graph](https://github.com/joshbuchea/HEAD/graphs/contributors). I'm not interested in adding any new files at this time. Thanks!

**Comment by tomlutzenberger** [comment]
IMHO a "Contributing.md", should contain rules and infos developers need to contribute, nothing else.
See [Twitter Bootstrap Contributing.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

**Comment by marcobiedermann** [comment]
@Oluwasetemi I suggest moving `./CONTRIBUTING.md` to `.github/CONTRIBUTING.md` subdirectory.
This avoids cluttering the root folder when more contributing related files are added.

See https://github.com/blog/2111-issue-and-pull-request-templates for more information

**Comment by joshbuchea** [comment]
Like @tomlutzenberger, I also expect a `Contributing.md` file to contain information about _how_ to contribute, as opposed to _who_ contributed.

**Comment by joshbuchea** [comment]
Also, I've added contributors section to the README with a link to the contributors graph.

**Pull request closed without merging**
