### PR TITLE
Added "Common JavaScript libraries" + jQuery

### PR DESCRIPTION
**Pull request by TwinProduction**
Added "Common JavaScript libraries" as well as "jQuery" as a subcategory.

### CODE REVIEW

**Comment by joshbuchea** [comment]
I think I'd prefer to not list common JS/CSS libraries. I feel like once we started down that road there would be no end. Demonstrating _how_ to include an external JS/CSS file is enough I believe.

I appreciate you limiting your PR to one change & updating the TOC though. Thanks @TwinProduction!

**Comment by ThaDafinser** [comment]
Yes, please do not include libraries.

**Comment by vonrac** [comment]
None of my business, and this is on a per-user basis, but I oppose links to CDNs. Privacy concerns and what not. I'd rather not give Google *another* point of data and have a slower web experience.

**Comment by joshbuchea** [comment]
@vonrac there are many non-Google CDNs. Also, common libraries loaded via CDN are often cached by the browser and actually load faster.

But point taken. Performance & privacy are valid reasons to not use a CDN.

**Comment by dodekeract** [comment]
@vonrac @joshbuchea you can actually vastly remove the impact CDNs have on privacy by using the relatively new [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) in all files you load from external servers. While that still doesn't prevent them from knowing which IP accessed the file, it does prevent them from modifying it.

**Pull request closed without merging**
