### PR TITLE
Updated author for google plus connect and added publisher meta tag

### PR DESCRIPTION
**Pull request by bhaskarmelkani**

### CODE REVIEW

**Comment by scottaohara** [comment]
why would you remove the humans.txt example though?

if it's a matter of not wanting to repeat the rel="author" then it'd make more sense to leave the href as a generic example than simply choose one equally valid example over another.

**Comment by bhaskarmelkani** [comment]
rel="author", is for adding Google Profile URL, to show your authorship for the page. I don't know the use case for humans.txt.

Can you please explain.

Thanks

**Comment by TraderStf** [comment]
http://microformats.org/wiki/rel-author

> Google will stop showing authorship results in Google Search, and will no longer be tracking data from content using rel=author markup.

**Comment by scottaohara** [comment]
@bhaskarmelkani see: http://humanstxt.org/

**Comment by joshbuchea** [comment]
Closing because [It’s Over: The Rise & Fall Of Google Authorship For Search Results](http://searchengineland.com/goodbye-google-authorship-201975) & [this Google+ post](https://plus.google.com/u/0/+JohnMueller/posts/HZf3KDP1Dm8). If I misunderstood or misinterpreted these announcements, feel free to re-open.

**Pull request closed without merging**
