### PR TITLE
import `Web component` and `dns-prefetch` via link tag

### PR DESCRIPTION
**Pull request by yPangXie**

### CODE REVIEW

**Comment by joshbuchea** [comment]
@yPangXie I added `dns-prefetch` in another commit. I'd be more than happy to accept a commit with the HTML import. Please update or submit a new pull request and I'll accept.

**Comment by joshbuchea** [comment]
Thanks @yPangXie!

**Comment by joshbuchea** [comment]
I went ahead and added the HTML import tag. Thanks for the contribution @yPangXie!

**Comment by yPangXie** [comment]
Awesome!

**Pull request closed without merging**
