### PR TITLE
fix #98 - add notes section with performance tip

### LINKED ISSUE #98: Info about gzip + attribute order
@marcobiedermann raised an important issue with #80 regarding gzip and attribute order. Per @scottaohara's recommendation, I would like to: 

> add a note / section that calls out best practice for actual implementation of these elements, and their attribute order

It would be great if @marcobiedermann wanted to tackle this. But, I'll go ahead and through a **help wanted** label on it in case anyone else would like to submit a PR. Thanks!

### PR DESCRIPTION
**Pull request by marcobiedermann**

### CODE REVIEW

**Comment by joshbuchea** [comment]
Looks good 👍 Thanks @marcobiedermann!

**Comment by joshbuchea** [comment]
Appreciate the extra effort.

**Comment by HubleGiter** [comment]
#

**Comment by marcobiedermann** [comment]
@joshbuchea You are very welcome. I am glad to help you out :)

**Comment by sammydigits** [comment]
@marcobiedermann do you have a source for this information please?

**Comment by sammydigits** [comment]
@marcobiedermann nice, thanks a lot for the links!

**Pull request merged**
